#page title
page_title                                : "Bookology: Book Tracker For Book Lovers"                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6747273681                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://bookology.app                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/darkicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bookology                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : All your books. All your notes. One place.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Empty Studio                                
your_link                                 : https://empty.mt                     
your_city                                 :                                 
email_address                             : bookologyapp@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : bookology.app
twitter_username                          : em_tystudio
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Beautiful & Minimal Design
    description                           : Enjoy a distraction-free interface that makes tracking and reviewing your books a pleasure.
    fontawesome_icon_name                 : magic
    
  - title                                 : Reading Progress Tracker
    description                           : Track your reading status and progress with ease — from “Want to Read” to “Finished.”
    fontawesome_icon_name                 : tasks

  - title                                 : Smart Notes & Highlights
    description                           : Capture your thoughts with rich text notes or OCR from book pages. Never lose an insight again.
    fontawesome_icon_name                 : sticky-note

  - title                                 : Review & Rating System
    description                           : Log your impressions after each book. Write detailed reviews and rate with customizable scores.
    fontawesome_icon_name                 : star

  - title                                 : Library & Shelf Management
    description                           : Organize your collection with categories like Reading, Abandoned, or Favorite. Your bookshelf, your way.
    fontawesome_icon_name                 : book
  
  - title                                 : Insightful Reading Stats
    description                           : Understand your habits with clean visualizations — reading time, pages per day, and more.
    fontawesome_icon_name                 : chart-bar

  - title                                 : iCloud Sync
    description                           : Securely sync your reading data across devices with iCloud. Always up to date.
    fontawesome_icon_name                 : cloud

  - title                                 : No Community, No Noise
    description                           : Focus on your reading journey without distractions. No feeds, likes, or followers — just books.
    fontawesome_icon_name                 : volume-mute

  - title                                 : Built for Readers, Not Algorithms
    description                           : Bookology is a tool, not a platform. Designed to support your reading, not capture your attention.
    fontawesome_icon_name                 : heart

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings

body_background_color                     : "#000000"

link_color                                : "#ffffff"



# Analytics
analytics_google_id                       : G-RXCRPKRGG3














####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
